.PHONY: clean All

All:
	@echo "----------Building project:[ labb44 - Debug ]----------"
	@cd "labb44" && "$(MAKE)" -f  "labb44.mk" && "$(MAKE)" -f  "labb44.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ labb44 - Debug ]----------"
	@cd "labb44" && "$(MAKE)" -f  "labb44.mk" clean
