.PHONY: clean All

All:
	@echo "----------Building project:[ Game2048 - Debug ]----------"
	@cd "Game2048" && "$(MAKE)" -f  "Game2048.mk" && "$(MAKE)" -f  "Game2048.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Game2048 - Debug ]----------"
	@cd "Game2048" && "$(MAKE)" -f  "Game2048.mk" clean
